// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouthCenterWeb.Data;

#nullable disable

namespace YouthCenterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422091848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YouthCenterWeb.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<int>("YouthCenterId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("youthCenterId");

                    b.HasKey("Id");

                    b.HasIndex("YouthCenterId");

                    b.ToTable("Activities");

                    b.HasAnnotation("Relational:JsonPropertyName", "activities");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasJsonPropertyName("endTime");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasJsonPropertyName("startTime");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasJsonPropertyName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("totalPrice");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("userId");

                    b.Property<int>("YouthCenterId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("youthCenterId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.HasIndex("YouthCenterId");

                    b.ToTable("Reservations");

                    b.HasAnnotation("Relational:JsonPropertyName", "reservations");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("nameAr");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("nameEn");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasAnnotation("Relational:JsonPropertyName", "role");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasJsonPropertyName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("name");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("roleId");

                    b.Property<int>("YouthCenterId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("youthCenterId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("YouthCenterId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.YouthCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("address");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasJsonPropertyName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasJsonPropertyName("name");

                    b.Property<decimal?>("PricePerHour")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("pricePerHour");

                    b.HasKey("Id");

                    b.ToTable("YouthCenters");

                    b.HasAnnotation("Relational:JsonPropertyName", "youthCenter");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.Activity", b =>
                {
                    b.HasOne("YouthCenterWeb.Models.YouthCenter", "YouthCenter")
                        .WithMany("Activities")
                        .HasForeignKey("YouthCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YouthCenter");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.Reservation", b =>
                {
                    b.HasOne("YouthCenterWeb.Models.Activity", "Activity")
                        .WithMany("Reservations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YouthCenterWeb.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YouthCenterWeb.Models.YouthCenter", "YouthCenter")
                        .WithMany("Reservations")
                        .HasForeignKey("YouthCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");

                    b.Navigation("YouthCenter");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.User", b =>
                {
                    b.HasOne("YouthCenterWeb.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouthCenterWeb.Models.YouthCenter", "YouthCenter")
                        .WithMany("Users")
                        .HasForeignKey("YouthCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("YouthCenter");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.Activity", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("YouthCenterWeb.Models.YouthCenter", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Reservations");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
